### ISSUE TITLE
Multi Camera Multi Tracking improving Reid accuracy

### ISSUE THREAD

**Issue by duggydoo** [openvinotoolkit/training_extensions#1039]
Hi,

Is there a way to improve the Reid accuracy? When we deploy to different sites we never have the same angles, the same lighting conditions (even between cameras). Is there any tool/solution to improve the model reidentification accuracy or the person identification accuracy per site or per camera? We get a lot of chairs being identified as people, reidentification drops and reconnects (sometimes) and between cameras (angles, lighting conditions etc) reid isn't fantastic (cannot track a person between cameras reliably). 

Wondering if there was a solution or tool that we can run per site, per camera in order to improve reid and person identification accuracy.

Much appreciated.

**Comment by vladimir-dudnik** [comment]
transferring to OTE for model fine tuning related questions

**Comment by sungmanc** [comment]
Close this issue, please reopen it if there is any problem.
