### ISSUE TITLE
pretrained model for PoseEstimationWithMobileNet

### ISSUE THREAD

**Issue by ywchan2005** [openvinotoolkit/training_extensions#127]
Hi.

Regarding human pose estimation, besides the pretrained model for multiperson pose estimation (PoseEstimationWithMobileNet), would there be a pretrained model for single person pose estimaiton (SinglePersonPoseEstimationWithMobileNet) as well?

Thanks.

**Comment by AlexanderDokuchaev** [comment]
@Daniil-Osokin

**Comment by Daniil-Osokin** [comment]
Hi,
We are going to add support of MS COCO dataset for the single-person pose estimation and release pre-trained model. Stay tuned and don't forget to star this repo =).

**Comment by Daniil-Osokin** [comment]
Hi, the model and demo are going to be merged, check https://github.com/opencv/open_model_zoo/pull/621.

**Comment by Daniil-Osokin** [comment]
@Ilya-Krylov Thanks for the housekeeping :smiley:.
