### ISSUE TITLE
How to implement asymmetric mode qunatization?

### ISSUE THREAD

**Issue by dongzhen123** [openvinotoolkit/training_extensions#131]
Hi,thanks for this great repo!  I'm wondering how to implement asymmetric mode qunatization.The default mode is symmetric mode.

**Comment by AlexanderDokuchaev** [comment]
@AlexKoff88

**Comment by AlexKoff88** [comment]
Hi,

We are working on the asymmetric scheme. Please follow the changes. It will come in the next release soon.
