### ISSUE TITLE
Custom IR model fails in MYRIAD.

### ISSUE THREAD

**Issue by katakissof** [openvinotoolkit/training_extensions#156]
**Describe the bug**

Hello,

I have trained a model in VOC with the pytorch toolkit of the openvino training extensions and I converted into onnx format with the provided utilities of the integrated nncf package. Afterwards, I converted the onnx file it into the IR representation and ran the benchmark app of the openvino.
It worked in the CPU but failed in the MYRIAD plugin with the following error:

**[ ERROR ] AssertionFailed: data->numConsumers() > 0**

I attach you the zip file with the IR model and the log file of the benchmark app.
Can you explain me why it fails ?

Thank you in advance.

**Steps to Reproduce**

1. Download the files from the above link:
https://www.dropbox.com/s/vodr2snbkd9fwht/material.zip?dl=0
2. Run the benchmark_app in the Inference Code of the above folder with the Myriad Plugin with provided IR model ( FP16 precision)
3. Also the onnx model and the original .pth model is provided for better debugging.

**Environment:**
 - OS:   Linux Ubuntu 18.04
 - Framework version:  PyTorch
 - Python version: 3.6
 - OpenVINO version: R2 and R3 has been tested

**Comment by AlexanderDokuchaev** [comment]
@katakissof Thank you for detailed description of the issue. 
It looks like problem in vpu plugin, i have reported to dev team.
I will keep you informed about any update.

**Comment by katakissof** [comment]
@AlexanderDokuchaev Thank you for your time. 
Please keep me updated.

**Comment by AlexanderDokuchaev** [comment]
@katakissof Bug was fixed. In next OpenVINO release it will work correctly.
