### ISSUE TITLE
LPRNet model evaluation(tools/eval.py) ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by olegshentz1** [openvinotoolkit/training_extensions#167]
Hi, thanks for this great rep

I'm following LPRNet: License Plate Recognition(CPU) guide. I've prepared dataset based on 8k numeric only vehicle plates. Currently I've reached 209000 / 250000 iteration, but when using `python3 tools/eval.py chinese_lp/config.py` to start evaluation process got ZeroDivisionError.

**Stacktrace:** 
>  Traceback (most recent call last):
  File "tools/eval.py", line 174, in <module>
    tf.app.run(main)
  File "/home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tools/eval.py", line 170, in main
    validate(cfg)
  File "tools/eval.py", line 140, in validate
    tf.Summary(value=[tf.Summary.Value(tag='evaluation/acc', simple_value=float(mean_accuracy / num)),
ZeroDivisionError: float division by zero

**The terminal output:**

> WARNING:tensorflow:From tools/eval.py:53: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:190: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:199: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:199: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:202: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From tools/eval.py:38: TextLineReader.__init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
WARNING:tensorflow:From tools/eval.py:48: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From tools/eval.py:84: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From tools/eval.py:87: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
2019-10-27 14:09:01.524225: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-27 14:09:01.546937: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2712000000 Hz
2019-10-27 14:09:01.547231: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x22bed10 executing computations on platform Host. Devices:
2019-10-27 14:09:01.547248: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From tools/eval.py:101: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:`tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/model/model.ckpt-209000.ckpt
GT label fails: 10002898
GT label fails: 10002936
GT label fails: 1000546
GT label fails: 10002267
GT label fails: 1001394
GT label fails: 10003908
GT label fails: 10002635
GT label fails: 10000048
GT label fails: 10002384
GT label fails: 10002031
GT label fails: 10003819
GT label fails: 10001808
GT label fails: 1002304
GT label fails: 10002396
GT label fails: 1001353
GT label fails: 10000918
GT label fails: 10002725
GT label fails: 1002142
GT label fails: 10000493
GT label fails: 1003345
GT label fails: 10001589
GT label fails: 10002119
GT label fails: 1003271
GT label fails: 10002378
GT label fails: 10000417
GT label fails: 1003082
GT label fails: 10000873
GT label fails: 1000182
GT label fails: 1001581
GT label fails: 1002264
GT label fails: 1000551
GT label fails: 1000237
GT label fails: 1003602
GT label fails: 10002089
GT label fails: 1002935
GT label fails: 1002678
GT label fails: 10003173
GT label fails: 1001547
GT label fails: 1002028
GT label fails: 1003043
GT label fails: 1000977
GT label fails: 1002087
GT label fails: 10000391
GT label fails: 1003363
GT label fails: 10003695
GT label fails: 1000385
GT label fails: 10002303
GT label fails: 10003081
GT label fails: 10002244
GT label fails: 10000527
GT label fails: 1001206
GT label fails: 1001512
GT label fails: 1003981
GT label fails: 10002101
GT label fails: 10003316
GT label fails: 10003582
GT label fails: 10003934
GT label fails: 1001628
GT label fails: 1003915
GT label fails: 10002390
GT label fails: 10003749
GT label fails: 1003729
GT label fails: 1001055
GT label fails: 1003415
GT label fails: 1001338
GT label fails: 10001389
GT label fails: 10003928
GT label fails: 1003445
GT label fails: 10003967
GT label fails: 1003297
GT label fails: 1003211
GT label fails: 1001340
GT label fails: 10003567
GT label fails: 10002065
GT label fails: 1002887
GT label fails: 1002692
GT label fails: 10001737
GT label fails: 1001179
GT label fails: 10001246
GT label fails: 1000672
Traceback (most recent call last):
  File "tools/eval.py", line 174, in <module>
    tf.app.run(main)
  File "/home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tools/eval.py", line 170, in main
    validate(cfg)
  File "tools/eval.py", line 140, in validate
    tf.Summary(value=[tf.Summary.Value(tag='evaluation/acc', simple_value=float(mean_accuracy / num)),
ZeroDivisionError: float division by zero

**Environment:**
- OS: Linux Ubuntu 18.04
- Python version: 3.6.8
- OpenVINO version: 2019 R3
- Using CPU tensorflow model

Thanks,
Oleg

**Comment by AlexanderDokuchaev** [comment]
Hi @olegshentz1 
Looks like you have annotated labels which do not match [paterns](https://github.com/opencv/openvino_training_extensions/blob/1c4db62e56069067563f8c22c3e030164e03282f/tensorflow_toolkit/lpr/lpr/utils.py#L27).

**Comment by olegshentz1** [comment]
> Hi @olegshentz1
> Looks like you have annotated labels which do not match [paterns](https://github.com/opencv/openvino_training_extensions/blob/1c4db62e56069067563f8c22c3e030164e03282f/tensorflow_toolkit/lpr/lpr/utils.py#L27).

Thanks a lot. I made that successfully.
But now while running the eval.py file for validation  it is checking GT Label and then after showing Test acc and Time per step,it is printing "|||||....." and the validation process is not ending.

> WARNING:tensorflow:From tools/eval.py:53: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From /home/ubuntu/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From /home/ubuntu/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:190: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
WARNING:tensorflow:From /home/ubuntu/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:199: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/ubuntu/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:199: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/ubuntu/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:202: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From tools/eval.py:38: TextLineReader.__init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
WARNING:tensorflow:From tools/eval.py:48: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
WARNING:tensorflow:From /home/ubuntu/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/ubuntu/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From tools/eval.py:84: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From tools/eval.py:87: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From /home/ubuntu/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
2019-10-28 08:22:56.211649: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-28 08:22:56.234842: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2019-10-28 08:22:56.235222: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x201f980 executing computations on platform Host. Devices:
2019-10-28 08:22:56.235265: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From tools/eval.py:101: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:`tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.
WARNING:tensorflow:From /home/ubuntu/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /home/ubuntu/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/model/model.ckpt-51.ckpt
Check GT label: 10000009
10000009 --  Edit Distance: 8
Test acc: 0.0
Test acc-1: 0.0
Time per step: 0.06437230110168457 for test size 1
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||..........                                                                                
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||.........                                                                                
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||........                                                                                
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||.......                                                                                
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||......                                                                                
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||...       


Is it correct processing? Do you have any suggestions why it takes so long time?

Thanks,
Oleg

**Comment by AlexanderDokuchaev** [comment]
> Thanks a lot. I made that successfully.
Great

> Is it correct processing?
Yes, the eval process is waiting new checkpoint from training process.
`train.py` and `eval.py` scripts should be runed in two terminals in one time.

**Comment by olegshentz1** [comment]
> Yes, the eval process is waiting new checkpoint from training process.
train.py and eval.py scripts should be runed in two terminals in one time.

Thanks a lot!

But there is still problem with running the model via OpenVINO on Raspberry Pi.
When using `python3 tools/export.py --data_type FP16 --output_dir model/export chinese_lp/config.py` I get three files `lpr.bin lpr.mapping lpr.xml`

**The terminal output:**

> /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/model/model.ckpt-750.ckpt
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From tools/export.py:51: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From tools/export.py:53: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
2019-10-29 16:34:04.818373: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-29 16:34:04.838346: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2712000000 Hz
2019-10-29 16:34:04.838625: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2261790 executing computations on platform Host. Devices:
2019-10-29 16:34:04.838644: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/model/model.ckpt-750.ckpt
WARNING:tensorflow:From tools/export.py:60: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/venv/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
INFO:tensorflow:Froze 66 variables.
INFO:tensorflow:Converted 66 variables to const ops.

> mo.py --framework=tf --input_model=model/export/frozen_graph/graph.pb.frozen --output_dir=model/export/IR/FP16 --framework=tf --model_name=lpr --input=input --output=d_predictions --reverse_input_channels --scale=255 --input_shape=[1,24,94,3] --data_type=FP16
> Model Optimizer arguments:
> Common parameters:
> 	- Path to the Input Model: 	/home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/model/export/frozen_graph/graph.pb.frozen
> 	- Path for generated IR: 	/home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/model/export/IR/FP16
> 	- IR output name: 	lpr
> 	- Log level: 	ERROR
> 	- Batch: 	Not specified, inherited from the model
> 	- Input layers: 	input
> 	- Output layers: 	d_predictions
> 	- Input shapes: 	[1,24,94,3]
> 	- Mean values: 	Not specified
> 	- Scale values: 	Not specified
> 	- Scale factor: 	255.0
> 	- Precision of IR: 	FP16
> 	- Enable fusing: 	True
> 	- Enable grouped convolutions fusing: 	True
> 	- Move mean values to preprocess section: 	False
> 	- Reverse input channels: 	True
> TensorFlow specific parameters:
> 	- Input model in text protobuf format: 	False
> 	- Path to model dump for TensorBoard: 	None
> 	- List of shared libraries with TensorFlow custom layers implementation: 	None
> 	- Update the configuration file with input/output node names: 	None
> 	- Use configuration file used to generate the model with Object Detection API: 	None
> 	- Operations to offload: 	None
> 	- Patterns to offload: 	None
> 	- Use the config file: 	None
> Model Optimizer version: 	2019.3.0-375-g332562022
> 
> [ SUCCESS ] Generated IR model.
> [ SUCCESS ] XML file: /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/model/export/IR/FP16/lpr.xml
> [ SUCCESS ] BIN file: /home/oleg/Documents/openvino_training_extensions/tensorflow_toolkit/lpr/model/export/IR/FP16/lpr.bin
> [ SUCCESS ] Total execution time: 5.04 seconds.


But when I try to run the model via OpenVINO on Raspberry Pi using 
`./armv7l/Release/security_barrier_camera_demo -i /home/pi/Downloads/333.jpg -m /home/pi/models/vehicle-license-plate-detection-barrier-0106.xml -d MYRIAD -m_va /home/pi/models/vehicle-attributes-recognition-barrier-0039.xml -d_va MYRIAD -m_lpr /home/pi/models/lpr.xml -d_lpr MYRIAD`

I get **`[ ERROR ] Error reading network: cannot parse future versions: 6**

**The terminal output:**

> [ INFO ] InferenceEngine:
API version ............ 1.6
Build .................. 22443
[ INFO ] Parsing input parameters
[ INFO ] Capturing video streams from the video files or loading images
[ INFO ] Files were added: 1
[ INFO ]     /home/pi/Downloads/333.jpg
[ INFO ] Number of input image files: 1
[ INFO ] Number of input video files: 0
[ INFO ] Number of input channels: 1
[ INFO ] Display resolution: 1920x1080
[ INFO ] Loading plugin MYRIAD

> 
> API version ............ 1.6
> Build .................. 22443
> Description ....... myriadPlugin
> [ INFO ] Loading network files for VehicleDetection
> [ INFO ] Batch size is forced to  1
> [ INFO ] Checking Vehicle Detection inputs
> [ INFO ] Checking Vehicle Detection outputs
> [ INFO ] Loading Vehicle Detection model to the MYRIAD plugin
> [ INFO ] Loading network files for VehicleAttribs
> [ INFO ] Batch size is forced to 1 for Vehicle Attribs
> [ INFO ] Checking VehicleAttribs inputs
> [ INFO ] Checking Vehicle Attribs outputs
> [ INFO ] Loading Vehicle Attribs model to the MYRIAD plugin
> [ INFO ] Loading network files for Licence Plate Recognition (LPR)
> [ ERROR ] Error reading network: cannot parse future versions: 6

Maybe I need to convert trained data to model in different way?

Thanks,
Oleg

**Comment by AlexanderDokuchaev** [comment]
@olegshentz1 
You have too old version on Raspberry Pi, `22443` build is `2019 R1`.
Update OpenVINO to 2019R3 (latest), it should fix this problem.

**Comment by olegshentz1** [comment]
Thanks.

I've downloaded a  OpenVINO to 2019R3 `(l_openvino_toolkit_runtime_raspbian_p_2019.3.334.tgz)` but there's no  Security Barrier Camera sample. I tried to take Security Barrier Camera sample from R1 version and install with R3 but it throws error.

**Comment by brmarkus** [comment]
It's now publicly available in the "Open Model Zoo":
https://github.com/opencv/open_model_zoo/tree/master/demos/security_barrier_camera_demo

**Comment by olegshentz1** [comment]
@AlexanderDokuchaev 

> Oh, i was fixed it some time ago and forget create PR with fix.
AlexanderDokuchaev/open_model_zoo@adc45bb

I took` net_wrappers.hpp`  form your fork and rebuild `/security_barrier_camera_demo` with it. Now on Ubuntu everything works fine. Thanks!

I've tried to do the same on Raspberry Pi using:
`./security_barrier_camera_demo -i /home/pi/Downloads/car-detection3.mp4 -m /home/pi/models/vehicle-license-plate-detection-barrier-0106.xml -d MYRIAD -m_va /home/pi/models/vehicle-attributes-recognition-barrier-0039.xml -d_va MYRIAD -m_lpr /home/pi/models/license-plate-recognition-barrier-0001.xml -d_lpr MYRIAD`

 I still get the same error.

**The terminal output:**

> [ INFO ] InferenceEngine:
API version ............ 2.1
Build .................. custom_releases/2019/R3_cb6cad9663aea3d282e0e8b3e0bf359df665d5d0
Description ....... API
[ INFO ] Files were added: 1
[ INFO ]     /home/pi/Downloads/car-detection3.mp4
*** Error in `./security_barrier_camera_demo': munmap_chunk(): invalid pointer: 0x016cd8




`It's harder, Could you find the line that failed?`

Can you explain me how I can do it? Because in terminal output there is no print of line that failed.

**Comment by AlexanderDokuchaev** [comment]
> Can you explain me how I can do it? 

The oldest and simplest debug method `std::cout << "line N" << std::endl;` :smile: 

But firstly, you can try install OpenVINO R2. May be some component for Raspberry Pi was build incorrectly in R3.

**Comment by olegshentz1** [comment]
@AlexanderDokuchaev 

I installed `OpenVINO R2`. Recompiled `open_model_zoo`. But I still have the same problem when I try to run default pre-trained models with `security_barrier_camera_demo` :

> ./security_barrier_camera_demo -i /home/pi/Downloads/car-detection3.mp4 -m /home/pi/models/vehicle-license-plate-detection-barrier-0106.xml -d MYRIAD -m_va /home/pi/models/vehicle-attributes-recognition-barrier-0039.xml -d_va MYRIAD -m_lpr /home/pi/models/license-plate-recognition-barrier-0001.xml -d_lpr MYRIAD

**The terminal output:**
> [ INFO ] InferenceEngine:
API version ............ 2.1
Build .................. custom_releases/2019/R3_cb6cad9663aea3d282e0e8b3e0bf359df665d5d0
Description ....... API
[ INFO ] Files were added: 1
[ INFO ]     /home/pi/Downloads/car-detection3.mp4
*** Error in `./security_barrier_camera_demo': munmap_chunk(): invalid pointer: 0x016cd8

:(

**Comment by AlexanderDokuchaev** [comment]
@olegshentz1 
Ok, another way, try to use image instead of video as input.

**Comment by olegshentz1** [comment]
@AlexanderDokuchaev 
When I use image instead of video I get Segmentation fault

`./security_barrier_camera_demo -i /home/pi/Downloads/1.jpg -m /home/pi/models/vehicle-license-plate-detection-barrier-0106.xml -d MYRIAD -m_va /home/pi/models/vehicle-attributes-recognition-barrier-0039.xml -d_va MYRIAD -m_lpr /home/pi/models/license-plate-recognition-barrier-0001.xml -d_lpr MYRIAD`

**The terminal output:**
> [ INFO ] InferenceEngine:
API version ............ 2.0
Build .................. custom_releases/2019/R2_f5827d4773ebbe727c9acac5f007f7d94dd4be4e
Description ....... API
[ INFO ] Files were added: 1
[ INFO ]     /home/pi/Downloads/1.jpg
[ INFO ] Loading device MYRIAD
MYRIAD
myriadPlugin version ......... 2.0
Build ........... 27579

> [ INFO ] Loading detection model to the MYRIAD plugin
> Segmentation fault

**Comment by olegshentz1** [comment]
@AlexanderDokuchaev 

> Return R3, and try again with image.

I get the same error with image.

`./security_barrier_camera_demo -i /home/pi/Downloads/1.jpg -m /home/pi/models/vehicle-license-plate-detection-barrier-0106.xml -d MYRIAD -m_va /home/pi/models/vehicle-attributes-recognition-barrier-0039.xml -d_va MYRIAD -m_lpr /home/pi/models/license-plate-recognition-barrier-0001.xml -d_lpr MYRIAD`


**The terminal output:**

> [ INFO ] InferenceEngine:
API version ............ 2.1
Build .................. custom_releases/2019/R3_cb6cad9663aea3d282e0e8b3e0bf359df665d5d0
Description ....... API
[ INFO ] Files were added: 1
[ INFO ]     /home/pi/Downloads/1.jpg
[ INFO ] Loading device MYRIAD
MYRIAD
myriadPlugin version ......... 2.1
Build ........... 30677

> [ INFO ] Loading detection model to the MYRIAD plugin
Segmentation fault


`I will try find RasberryPi and reproduce it. But i'm need some time.`
Thanks! I'll be waiting for your comment

**Comment by olegshentz1** [comment]
@AlexanderDokuchaev Hi. Is there any news about issue?

**Comment by dkurt** [comment]
@olegshentz1, can you share build instructions? Have you considered `-march=armv7-a` compiler flag? (source https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_raspbian.html)

**Comment by olegshentz1** [comment]
@dkurt 
Hi. I've build openvino for raspbian using this guide 
( https://docs.openvinotoolkit.org/2019_R3/_docs_install_guides_installing_openvino_raspbian.html )


>  Have you considered -march=armv7-a compiler flag?

No. I have not use` -march=armv7-a`. I'll try to set `-march=armv7-a` compiler flag

Thanks.

**Comment by richardgohth** [comment]
Can LPRNet read  2 row plates? ie plates with 2 rows, found in some countries
thanks
