### ISSUE TITLE
[Text detection] Training step is very slow?

### ISSUE THREAD

**Issue by FLming** [openvinotoolkit/training_extensions#168]
I use 2x 1080Ti or 8x GTX TITIAN X computer to train a model by using this repo code, but the model.fit function is very slow on the machine. I try to find why and change the code, the speed still can't be improved. The Intuition tells me that this speed is not normal.

**Comment by Ilya-Krylov** [comment]
@FLming you can try to disable `ExponentialMovingAverageCallback`
