### ISSUE TITLE
How to set correct parameters for conversion ONNX to OpenVINO format? (action recognition in PyTorch toolkit)

### ISSUE THREAD

**Issue by hiankun** [openvinotoolkit/training_extensions#169]
Hi, I was trying to follow [the instrument of converting pre-trained models to ONNX and OpenVINO format](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/action_recognition). Also, I tried to apply [some useful information given in the thread](https://github.com/opencv/openvino_training_extensions/issues/103) to convert the models to `encoder` and `decoder` so that I will be able to run them with my NCS 2.

The following are steps I've tried. Some steps were successful, some were failed and need help from you.

## Download pre-trained models
I downloaded the following two models to try the conversion scripts:
* `resnet_34_vtn_rgb_kinetics.pth`
* `resnet_34_vtn_rgbd_kinetics.pth`

## Convert to ONNX
I used the following command to convert the downloaded models:

* For the __encoder__ of  `resnet_34_vtn_rgb_kinetics.pth`:
  ```
  python3 main.py \                                                               
  --clip-size 16 \                                                              
  --st 2 \                                                                      
  --model resnet34_vtn_encoder \           
  --pretrain-path ./pretrained_models/resnet_34_vtn_rgb_kinetics.pth \          
  --onnx ./pretrained_models/resnet34_vtn_rgb_encoder.onnx 
  ```
* For the __decoder__ of  `resnet_34_vtn_rgb_kinetics.pth`:
  ```
  python3 main.py \                                                               
  --clip-size 16 \                                                              
  --st 2 \                                                                      
  --model resnet34_vtn_decoder \                                                
  --pretrain-path ./pretrained_models/resnet_34_vtn_rgb_kinetics.pth \          
  --onnx ./pretrained_models/resnet34_vtn_rgb_decoder.onnx 
  ```
* For `resnet_34_vtn_rgbd_kinetics.pth`, failed to convert it to encoder and decoder separately.
  * I have tried to use something like `resnet34_vtn_rgbdiff_encoder` but the script returned `KeyError`.
  * I followed the error message to check available model name and found `vtn_rgbdiff` has no `encoder` or `decoder` items. 

## Convert to OpenVINO format
Based on the above results, I continued to convert the ONNX models to OpenVINO format.

My __Model Optimizer__ version is `2019.3.0-375-g332562022` installed in __Ubuntu 18.04__.
                                                                                   
* For `resnet34_vtn_rgb_encoder.onnx`, the IR format was generated successfully by the following commands:
  ```                                                                              
  mo.py \                                                                          
  --data_type FP16 \                                                               
  --input_model ./pretrained_models/resnet34_vtn_rgb_encoder.onnx \                
  --input_shape '[1,3,224,224]'                                                    
  ```                                                                              
                                                                                   
* For `resnet34_vtn_rgb_decoder.onnx`, the following commands failed to generate IR files:
  ```                                                                              
  mo.py \                                                                          
  --data_type FP16 \                                                               
  --input_model ./pretrained_models/resnet34_vtn_rgb_decoder.onnx \                
  --input_shape '[1,16,512]'                                                       
  ```                                                                              
  * The corresponding error message was:                                        
    ```                                                                         
    [ ERROR ]  Cannot infer shapes or values for node "274/Broadcast".          
    [ ERROR ]  'numpy.float64' object cannot be interpreted as an integer       
    [ ERROR ]                                                                   
    [ ERROR ]  It can happen due to bug in custom shape infer function <function Broadcast.infer at 0x7fbe14c942f0>.
    [ ERROR ]  Or because the node inputs have incorrect values/shapes.         
    [ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
    [ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information. 
    [ ERROR ]  'numpy.float64' object cannot be interpreted as an integer       
    Stopped shape/value propagation at "274/Broadcast" node.                    
     For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 
     Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): 'numpy.float64' object cannot be interpreted as an integer
     Stopped shape/value propagation at "274/Broadcast" node.                   
      For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 
    ```                                                                         
* For `resnet34_vtn_rgbd.onnx`, use the following command and __got similar error message as the above one__.
  ```                                                                           
  mo.py \                                                                                                                                                                                     
  --data_type FP16 \                                                              
  --input_model ./pretrained_models/resnet34_vtn_rgbd.onnx \                                                                                                                                  
  --input_shape '[1,16,3,224,224]'                                              
  ```                                                                           
                                                                                
So far, I have the following downloaded and converted models:                   
                                                                                
| Downloaded | `resnet_34_vtn_rgb_kinetics.pth` | `resnet_34_vtn_rgbd_kinetics.pth` |
|---|---|---|                                                                   
| ONNX | `resnet34_vtn_rgb_encoder.onnx` | `resnet34_vtn_rgbd.onnx` |           
|| `resnet34_vtn_rgb_decoder.onnx` ||                                           
| OpenVINO | `resnet34_vtn_rgb_encoder.xml` and `resnet34_vtn_rgb_encoder.bin` ||

## Questions
1. What's the __encoder__ and __decoder__ `--model` name for `resnet_34_vtn_rgbd_kinetics.pth`? Or even for some other pre-trained models?
2. How to set proper parameters for converting to OpenVINO format? Was the error caused by wrong `--input_shape`?
3. Did I miss any critical parameters for the conversion scripts?

Hope my steps would be useful to someone who might face similar situations, and also hope my description is clear enough for you to give help or further information.

**Comment by dtoertei** [comment]
Hi,

I have the exact same problem when trying to compile ONNX decoder with OpenVINO and I am using the same parameters.
Maybe build information could help:
Torch version: 1.3.0
OpenVINO version: 2019.3.0-375-g332562022

Running with DEBUG option I get this:
...
[ 2019-11-14 13:51:40,619 ] [ DEBUG ] [ infer:32 ]  input[0]: shape = [1], value = [0]
[ 2019-11-14 13:51:40,619 ] [ DEBUG ] [ infer:32 ]  input[1]: shape = [1], value = [16]
[ 2019-11-14 13:51:40,619 ] [ DEBUG ] [ infer:144 ]  Outputs:
[ 2019-11-14 13:51:40,619 ] [ DEBUG ] [ infer:32 ]  output[0]: shape = [1], value = [16]
[ 2019-11-14 13:51:40,619 ] [ DEBUG ] [ infer:129 ]  --------------------
[ 2019-11-14 13:51:40,619 ] [ DEBUG ] [ infer:130 ]  Partial infer for 273/mul_
[ 2019-11-14 13:51:40,619 ] [ DEBUG ] [ infer:131 ]  Op: Mul
[ 2019-11-14 13:51:40,620 ] [ DEBUG ] [ infer:142 ]  Inputs:
[ 2019-11-14 13:51:40,620 ] [ DEBUG ] [ infer:32 ]  input[0]: shape = [1], value = [1.]
[ 2019-11-14 13:51:40,620 ] [ DEBUG ] [ infer:32 ]  input[1]: shape = [1], value = [16]
[ 2019-11-14 13:51:40,620 ] [ DEBUG ] [ infer:144 ]  Outputs:
[ 2019-11-14 13:51:40,620 ] [ DEBUG ] [ infer:32 ]  output[0]: shape = [1], value = [16.]
[ 2019-11-14 13:51:40,621 ] [ DEBUG ] [ infer:129 ]  --------------------
[ 2019-11-14 13:51:40,621 ] [ DEBUG ] [ infer:130 ]  Partial infer for 274/Broadcast
[ 2019-11-14 13:51:40,621 ] [ DEBUG ] [ infer:131 ]  Op: Broadcast
[ ERROR ]  Cannot infer shapes or values for node "274/Broadcast".
[ ERROR ]  'numpy.float64' object cannot be interpreted as an integer

Could you please help?

**Comment by dtoertei** [comment]
One "solution" is to set --layer-norm to False. and that way it is possible to compile the pytorch model correctly and obtain .xm and .bin files.

**Comment by Nhoodangggggg** [comment]
I got the same error when I tried to change decoder.onnx to IR file. Can you solve this problem? Could you give me some advices?

**Comment by minhhoangbui** [comment]
@vadimadr : Please have a look at this issue, after investigation, I cannot determine the cause

**Comment by minhhoangbui** [comment]
@all: I found the problem lie at this layer nn.Embedding, are there any way to avoid this?

**Comment by gmt710** [comment]
If anyone want to use vtn_demo or jpg's version, you can refer to [my chinese blog](https://blog.csdn.net/qq_35975447/article/details/112261368).
