### ISSUE TITLE
Will segmentoly python code for InstanceSegmentationSecurity0010 be made available

### ISSUE THREAD

**Issue by jimwormold** [openvinotoolkit/training_extensions#179]
I have successfully trained a segmentoly.rcnn.model_zoo.instance_segmentation_security_0050.InstanceSegmentationSecurity0050 on my own dataset and would like to compare with the InstanceSegmentationSecurity0010 model, but am unable to find  the equivalent python file/module (segmentoly.rcnn.model_zoo.instance_segmentation_security_0010.InstanceSegmentationSecurity0010).

Are there plans to provide one, or can someone provide a little guidance into what needs amending in the 0050 model.

Many thanks

**Comment by AlexanderDokuchaev** [comment]
Hi @jimwormold 

> I have successfully trained a segmentoly.rcnn.model_zoo.instance_segmentation_security_0050.InstanceSegmentationSecurity0050 on my own dataset and would like to compare with the InstanceSegmentationSecurity0010 model,

:+1: 

> but am unable to find the equivalent python file/module (segmentoly.rcnn.model_zoo.instance_segmentation_security_0010.InstanceSegmentationSecurity0010).

We dont find compromise how to store code for each models, as result we have two ways how to train it.
For `0010` and `0083` it general [train.py](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/instance_segmentation/tools/train.py) with different arguments, so for `0050` models it looks like separated script [train_0050.py](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/instance_segmentation/tools/train_0050.py).

You can find command line to train `instance_segmentation_security_0010` in [OpenVINO.md](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/instance_segmentation/OpenVINO.md)

**Comment by jimwormold** [comment]
Thanks very much for the speedy reply. I'll get cracking on that!

**Comment by dbAIStudio** [comment]
@jimwormold Hello, ask what is your setup environment, I will report an error when training according to the required environment,
AttributeError: module 'torch' has no attribute 'bool'
This error seems to be that there is no bool type in torch0.4.1
