### ISSUE TITLE
Loss Nan when training ssd for plate detection

### ISSUE THREAD

**Issue by ildarkin836** [openvinotoolkit/training_extensions#180]
Hello, i'm trying to train ssd detector on custom dataset, but loss -inf on step 1

**Comment by AlexanderDokuchaev** [comment]
Hi @ildarkin836 
Looks like incorrect format of annotation.
Ensure that your annnotation file have same format with [annotations_test.json](https://github.com/opencv/openvino_training_extensions/blob/develop/data/vlp_test/annotations_test.json).
