### ISSUE TITLE
does it support deformable convolution?

### ISSUE THREAD

**Issue by lemonyhw** [openvinotoolkit/training_extensions#181]

**Comment by AlexanderDokuchaev** [comment]
hi @lemonyhw 
Thank you for your interest in our project.

Do you ask about Neural Networks Compression Framework?

**Comment by lemonyhw** [comment]
No, in fact i want to covert CenterNet which includes deformable convolution.

**Comment by AlexanderDokuchaev** [comment]
If you want to convert CenterNet by model_optimizer, then answer is yes.
[List of suported layers](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html) 

More detailed you can find by https://github.com/opencv/dldt and
https://docs.openvinotoolkit.org/latest/_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html

**Comment by lemonyhw** [comment]
Thank you very much, I will try~~

**Comment by lemonyhw** [comment]
> If you want to convert CenterNet by model_optimizer, then answer is yes.
> [List of suported layers](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html)
> 
> More detailed you can find by https://github.com/opencv/dldt and
> https://docs.openvinotoolkit.org/latest/_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html

Thank you very much, I will try it~~
