### ISSUE TITLE
converting pth to onnx encoder and decoder (action recognition)

### ISSUE THREAD

**Issue by bagaseko1** [openvinotoolkit/training_extensions#182]
i have train my own model action recognition, but how to convert decoder and encoder onnx file.
it is my command line
python main.py --clip-size 16 --st 2 --model resnet34_vtn_encoder --pretrain-path save_200.pth --onnx resnet34_vtn_rgb_encoder.onnx --no-layer-norm --dataset ucf101_01
python main.py --clip-size 16 --st 2 --model resnet34_vtn_decoder --pretrain-path save_200.pth --onnx resnet34_vtn_rgb_decoder.onnx --no-layer-norm --dataset ucf101_01
it is work and success create onnx file and after i convert to IR use this command line 
python mo.py --data_type FP16 --input_model resnet34_vtn_rgb_encoder.onnx --input_shape [1,3,224,224] --output_dir E:/
python mo.py --data_type FP16 --input_model resnet34_vtn_rgb_decoder.onnx --input_shape [1,16,512] --output_dir E:/
convert is success, but i only get one prediction 
is my command line wrong or i miss something ?

**Comment by minhhoangbui** [comment]
@bagaseko1 Can you tell me your version of pytorch, numpy as well as openvino?
At the moment, I'm stuck at converting to openvino IR
