### ISSUE TITLE
Why I can't reproduce your results about | ResNet34-VTN| RGB | UCF101  | 90.27%|

### ISSUE THREAD

**Issue by JinYAnGHe** [openvinotoolkit/training_extensions#184]
I have two 2080Ti GPUs. I run the commad `python main.py --dataset ucf101_1 --model resnet34_vtn -b16 --lr 1e-5 --seq 16 --st 2 `
But the highest Video@1 is only 85% instead of 90.27% as you reported.
So I wonder what might be wrong with my training. Or I overlooked some of the training details you used？
Thanks for your wonderful project and it help me a lot whether I am at Intel or school. 
Looking forward to your guidance!

**Comment by minhhoangbui** [comment]
@JinYAnGHe Do you succeed to reproduce the result? I fail it too
I suspect they use some tricks to train the model since when I use their model to test, I got the result they reported
@vadimadr Can you help us here?

**Comment by vadimadr** [comment]
Hi! In order to reproduce the 90%+ result on UCF you need to start from pretrained on Kinetics model.

**Comment by minhhoangbui** [comment]
@vadimadr Thanks a lot for that tip, I'm not aware of that. 
I have another favour to ask: I fail to convert ONNX model of VTN to OpenVino IR too, and I use 2020.1
It works fine in case of Attention LSTM. Can you give me a hand?

**Comment by vadimadr** [comment]
It would be easier to help if you attached error log. My bling guess is that you use newer version of PyTorch that in turn uses newer version of ONNX operation set which is not yet fully compatible with model optimizer.

**Comment by minhhoangbui** [comment]
@vadimadr, this is the issue that I am talking about.
[https://github.com/opencv/openvino_training_extensions/issues/227](url)
Please take a look
