### ISSUE TITLE
Pytorch toolkit person vehicle bike detector folder missing

### ISSUE THREAD

**Issue by davidrij** [openvinotoolkit/training_extensions#185]
In the person vehicle bike tutorial for pytorch, the folder in step 1 does not exist in the repo:

_Go to openvino_training_extensions/pytorch_toolkit/crossroad_detector/ directory_

Also, the tutorial does not seem to work when training on a CPU.

Cheers!

**Comment by AlexanderDokuchaev** [comment]
@davidrij 
Thanks, paths was fixed.

For object detection used https://github.com/open-mmlab/mmdetection, and as i know training on cpu is not supported.
