### ISSUE TITLE
AttributeError: 'ImageDataManagerWithTransforms' object has no attribute 'return_dataloaders'

### ISSUE THREAD

**Issue by abhishek11097** [openvinotoolkit/training_extensions#203]
Hey, 
I am trying to train the person-reidentification-retail-0200.yaml model on market1501 model. Since I could not find msmt17 dataset, I changed the avl_datasets to just ['market1501']

While trying to run 
python3 main.py     --root root     --config config/person-reidentification-retail-0200.yaml

I am getting the following error 
AttributeError: 'ImageDataManagerWithTransforms' object has no attribute 'return_dataloaders'

Can anyone please help out in figuring out what am I doing wrong.

**Comment by AlexanderDokuchaev** [comment]
@sovrasov @DmitriySidnev

**Comment by sovrasov** [comment]
Probably you use inconsistent version of the torchreid library.
Did you follow the instructions from README and use virtual environment built by the `init_venv.sh` script?
