### ISSUE TITLE
pytorch'sinstance_segmentation

### ISSUE THREAD

**Issue by dbAIStudio** [openvinotoolkit/training_extensions#226]
Hello, I have this problem when I use Ubuntu 18 for training，Other packages are installed as required：module 'torch' has no attribute 'bool'，What's the reason？

**Comment by AlexanderDokuchaev** [comment]
Hi @dbAIStudio  
Please provide log of error message, command that you run and output of `pip3 show torch`.

**Comment by AlexanderDokuchaev** [comment]
Yes,it was because torch 0.4.1 has no bool type.
You can replace 'torch.bool to torch.uint8' or try to use newer version. 

Fix for this will be added soon.
