### ISSUE TITLE
human pose : train_single.py and val_single.py have  bugs

### ISSUE THREAD

**Issue by miaochenGuo** [openvinotoolkit/training_extensions#232]
**Describe the bug**

**Steps to Reproduce**

 1.train_single.py
       if you run it, there must be something wrong, class LipValDataset does not have a member num_keypoints. So we can add 'self.num_keypoints = 16' in dataset/lip.py. And it will be ok.

    2.val_single.py
       if you run it, something wrong, we have to correct it in row99,'val = [int(all_keypoints[id][1][0]), int(all_keypoints[id][1][1])]' , now it can be run successfully, but the result is wrong, so i guess there has something wrong with the model loading...

**Comment by AlexanderDokuchaev** [comment]
Hi @miaochenGuo 

Thanks for describe the bug. 
Now it works correctly, update repository to the latest commit.
