### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by zechendev** [openvinotoolkit/training_extensions#237]
when using the nncf/exapmles/detection/train.py to train the compression model, there is a RuntimeError occurs, which in main.py 'out = net(images)', RuntimeError: only Tensors of floating point dtype can require gradients.
pytorch version: 1.4.0

**Comment by AlexanderDokuchaev** [comment]
@AlexKoff88

**Comment by AlexKoff88** [comment]
@zechendev,  can you please provide any details on how did you get this error?
- Command-line arguments 
- Other possible steps, such as setup, HW environment, etc.

In the meantime, I suggest trying a previous recommended version of PyTorch 1.3.1.

**Comment by vshampor** [comment]
@zechendev, we can reproduce this problem and will fix it in the next NNCF release. Please use PyTorch 1.3.1 in the meanwhile.

**Comment by vshampor** [comment]
It turns out that there is a bug in the PyTorch 1.4.0 as released that precluded using integer non-trainable parameters in PyTorch modules. It was only fixed in PyTorch 1.5.0.
