### ISSUE TITLE
ERROR when convert ONNX to IR in Instance Segmentation

### ISSUE THREAD

**Issue by niuwenju** [openvinotoolkit/training_extensions#247]
i have successfully converted mask_rcnn_resnet50_fpn_2x.pkl to mask_rcnn_resnet50_fpn_2x.onnx
but when i convert mask_rcnn_resnet50_fpn_2x.onnx to mask_rcnn_resnet50_fpn_2x.xml and mask_rcnn_resnet50_fpn_2x.bin, got error as follows:

[ ERROR ]  Shape is not defined for output 3 of "639".
[ ERROR ]  Cannot infer shapes or values for node "639".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "639". 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #40. 
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function ExperimentalDetectronDetectionOutput.infer at 0x7f08d9360268>.

**Environment:**
 - OS:  Linux Ubuntu 18.04
 - Framework version: PyTorch
 - Python version: 3.5.2
 - OpenVINO version: 2020 1
 - CUDA/cuDNN version: 9.0/7.5
 - GPU model and memory: Intel® HD Graphics 530 (Skylake GT2)

and when use OpenVINO version: 2019 R3.1 it can successfully convert mask_rcnn_resnet50_fpn_2x.onnx to mask_rcnn_resnet50_fpn_2x.xml and mask_rcnn_resnet50_fpn_2x.bin, but there is also some error when run the dome 
     **python tools/demo.py     --dataset coco_2017_val     --ckpt pretrained_models/ir/coco/detectron/FP16/mask_rcnn_resnet50_fpn_2x.bin     --fit_window 800 1333     --video test1.mp4     --delay 1     --show_fps     openvino     --model pretrained_models/ir/coco/detectron/FP16/mask_rcnn_resnet50_fpn_2x.xml     --device GPU**

as follows:
     **RuntimeError: Unknown Layer Type: ExperimentalDetectronPriorGridGenerator
Exception ignored in: <bound method OpenVINONet.__del__ of <segmentoly.rcnn.openvino_net.MaskRCNNOpenVINO object at 0x7fbd4e800908>>
Traceback (most recent call last):
  File "/home/dcg/Downloads/instance_segmentation/segmentoly/rcnn/openvino_net.py", line 77, in __del__
    del self.exec_net
AttributeError: exec_net**

**Comment by AlexanderDokuchaev** [comment]
Hi @niuwenju 
 
> and when use OpenVINO version: 2019 R3.1 it can successfully convert mask_rcnn_resnet50_fpn_2x.onnx to mask_rcnn_resnet50_fpn_2x.xml and mask_rcnn_resnet50_fpn_2x.bin, but there is also some error when run the dome
python tools/demo.py --dataset coco_2017_val --ckpt pretrained_models/ir/coco/detectron/FP16/mask_rcnn_resnet50_fpn_2x.bin --fit_window 800 1333 --video test1.mp4 --delay 1 --show_fps openvino --model pretrained_models/ir/coco/detectron/FP16/mask_rcnn_resnet50_fpn_2x.xml --device GPU

GPU plugin does not support this model and looks like it will not be added in the future :disappointed: 


> i have successfully converted mask_rcnn_resnet50_fpn_2x.pkl to mask_rcnn_resnet50_fpn_2x.onnx
but when i convert mask_rcnn_resnet50_fpn_2x.onnx to mask_rcnn_resnet50_fpn_2x.xml and mask_rcnn_resnet50_fpn_2x.bin, got error as follows:
and when use OpenVINO version: 2019 R3.1 it can successfully convert mask_rcnn_resnet50_fpn_2x.onnx to mask_rcnn_resnet50_fpn_2x.xml and mask_rcnn_resnet50_fpn_2x.bin

It's issue with latest release, we will try to solve it.
