### ISSUE TITLE
Training bug for nnfc classification training 

### ISSUE THREAD

**Issue by YDS-FOREVER** [openvinotoolkit/training_extensions#254]
**Describe the bug**

I don't know why it quit training, did n' t report any mistakes.
**using Parameters:**
-m train --dataset cifar100 --config configs/binarization/resnet18_imagenet_bin_dorefa.json --data data/imagenet/ --resume ../../results/quantization/mobilenetv2_int8/resnet18_cifar100_binarization/2020-03-23__13-10-09/resnet18_cifar100_binarization_last.pth --log-dir=../../results/quantization/mobilenetv2_int8/
**The output:**

> ......
> Total binarized MAC share: 92.4%
> INFO:nncf.dynamic_graph.graph_builder:Building graph with context: create_compressed_graph
> => loading checkpoint '../../results/quantization/mobilenetv2_int8/resnet18_cifar100_binarization/2020-03-23__13-10-09/resnet18_cifar100_binarization_last.pth'
> Loaded 202/202 layers
> => loaded checkpoint '../../results/quantization/mobilenetv2_int8/resnet18_cifar100_binarization/2020-03-23__13-10-09/resnet18_cifar100_binarization_last.pth' (epoch: 10, best_acc1: 51.550)
> Files already downloaded and verified
> Files already downloaded and verified
> /root/app/remote_test/tmp/pycharm_project_386/nncf/nncf/dynamic_graph/patch_pytorch.py:182: UserWarning: You are using DataParallel, which may cause significant performance issues with dynamic graph building. Consider using distributed training (DistributedDataParallel) instead
>   warnings.warn("You are using DataParallel, which may cause significant performance issues with dynamic graph "
> INFO:nncf.binarization.layers:Binarized activation scale set to: 5.017900466918945
> 
> Process finished with exit code -1

Before, I have trained the model 9 epoch. when I resume the train ,thart's what happened.

**Comment by AlexanderDokuchaev** [comment]
@AlexKoff88 @vshampor @ljaljushkin

**Comment by vshampor** [comment]
Greetings, @yangdashi888 !

Sorry, I could not reproduce the issue while training from 0-th epoch. Perhaps you could post your .pth checkpoint?
