### ISSUE TITLE
Link for pretrained single person pose estimation model

### ISSUE THREAD

**Issue by Roboram** [openvinotoolkit/training_extensions#258]
The link provided for download in the Readme_single.md file doesn't work. Could you please share the correct link to download the pre-trained model for single person pose estimation '.pth' file

**Comment by AlexanderDokuchaev** [comment]
Hi @Roboram 
Do you mean that the link is broken or file?

**Comment by Roboram** [comment]
The link seems to be broken.

**Comment by AlexanderDokuchaev** [comment]
@Roboram 
It looks like issue that depends from location.
Do you can download another file from [download.01.org](https://download.01.org/opencv/openvino_training_extensions/models/)?

Temporal link for [single-human-pose-estimation-0001.pth](
https://drive.google.com/open?id=1zZa5cEgPis-Mqsaiam0DwFMwCsg8th92)
