### ISSUE TITLE
About ASL-recognition

### ISSUE THREAD

**Issue by AlexHu123** [openvinotoolkit/training_extensions#263]
1. As you mentioned, 'due to significant noise in the original annotation of MS-ASl dataset we use the cleanned version which includes ' Would you release the cleanned version?
2. Would you report the final accuracy of your released model?
3. Would you add 3D-ResNet-50 model trained on this dataset?
Thanks in advance!

**Comment by AlexanderDokuchaev** [comment]
@snosov1 @evgeny-izutov

**Comment by evgeny-izutov** [comment]
1. Sorry, we faced with insuperable legal issues on the way to share the cleaned annotation for the MS-ASL dataset.
2. The final model metrics you can find in the [paper](https://arxiv.org/abs/2004.05054).
3. We are focused on developing lightweight solutions but 3D-ResNet-50 is not of this number of models.
