### ISSUE TITLE
Creating Custom (Labelled) Data for Text Spotting (or text recognition)

### ISSUE THREAD

**Issue by ankitbansal811** [openvinotoolkit/training_extensions#299]
How can we create text recognition dataset using our custom images. This dataset should work text spotting module (using pytorch toolkit) given in this repo.

**Comment by AlexanderDokuchaev** [comment]
HI @ankitbansal811 

You can annotate image by annotation tools like [CVAT](https://github.com/opencv/cvat).
After you should ensure that annotation that you will get in same format that used in [datasets](
https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/text_spotting#download-datasets).
Next follow instructions [pytorch_toolkit/text_spotting](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/text_spotting).
