### ISSUE TITLE
clarify: is openvino a requirement for OTE/NNCF?

### ISSUE THREAD

**Issue by vladium** [openvinotoolkit/training_extensions#302]
Greetings. Hopefully, this is a trivial question. 

I am having a little trouble understanding to what extent (if any) NNCF requires openvino to be installed. There are multiple requirements.txt, readme.md, Dockerfiles, and other instruction-like documents in the repo, so:

1. is there a "canonical" way to install OTE and/or NNCF? For example, if I wanted to build a docker image for running NNCF tooling, where should I look for pointers?
2. since NNCF can export to ONNX and/or openVINO IR format, does that mean NNCF requires openVINO to be installed (e.g. into the Docker image I mention in #1)?

Thank you.

**Comment by AlexanderDokuchaev** [comment]
Hi @vladium 
1. To install NNCF follow [instruction in readme](https://github.com/openvinotoolkit/nncf_pytorch#installation). And you can find docker files in [https://github.com/openvinotoolkit/nncf_pytorch/tree/master/docker](https://github.com/openvinotoolkit/nncf_pytorch/tree/master/docker). 
2. Directly for model compression by NNCF, OpenVINO is not required. OpenVINO required to export model from ONNX to OpenVINO IR by [model_optimizer](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Config_Model_Optimizer.html) and inference by [Inference_Engine](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Deep_Learning_Inference_Engine_DevGuide.html).
