### ISSUE TITLE
pytorch_toolkit text_spotting extension on Windows10 WSL 

### ISSUE THREAD

**Issue by spiovesan** [openvinotoolkit/training_extensions#306]
I am trying to use pytorch_toolkit/text_spotting extension on a Windows10 WSL.
I run the `bash init_venv.sh` and build looks ok. Build log is attached
[log.txt](https://github.com/opencv/openvino_training_extensions/files/4715644/log.txt)
I activate the environment `. venv/bin/activate`, but when running `python3 tools/create_dataset.py` I get the error: 
```
import torch
ModuleNotFoundError: No module named 'torch'
```
What I am missing?

**Comment by AlexanderDokuchaev** [comment]
Hi @spiovesan 
We don`t use windows for training, our target platform Ubuntu only.

In you logs you can find that installation of `pycocotools` and `Polygon3` modules. And build of torch failed too. You can try to find a solution to build it on windows, but i recommend you try use Ubuntu.

**Comment by spiovesan** [comment]
Hi Alexander,
I am not using Windows to build but Ubuntu 16.04 LTS on [Windows10 WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). Any idea what caused the build of the three packages to fail?

**Comment by AlexanderDokuchaev** [comment]
Sorry we have no experience with WSL. I can only suggest you follow [init_vevn.sh](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/text_spotting/init_venv.sh) script step by step and look on errors and try to resolve it. 

You can run pip install with verbose output `pip install -v pycocotools` and look on error.
