### ISSUE TITLE
question about using “person-vehicle-bike-detection”

### ISSUE THREAD

**Issue by dhdljd** [openvinotoolkit/training_extensions#317]
Hi
I have installed mmdetection torch...manually. so I did not bash init_venv.sh
I downloaded the pretrained model file in the readme
person_vehicle_bike_sd512_mb2_clustered_epoch_21.pth
when I use mmdetection/tools/train.py or test.py
the result is 
Keyerror:'SSDMobilenetV2 is not in the backbone registry'
my question is:
this error is related to init_venv.sh must I bash init_venv.sh?
can I know why?

**Comment by AlexanderDokuchaev** [comment]
Hi @dhdljd 
You should install mmdetection from our fork https://github.com/opencv/mmdetection.
And yes, better use `bash init_venv.sh`.

**Comment by dhdljd** [comment]
> Hi @dhdljd
> You should install mmdetection from our fork https://github.com/opencv/mmdetection.
> And yes, better use `bash init_venv.sh`.
Thank you very much for your quickly reply.@AlexanderDokuchaev
I used bash init_venv.sh and now first problem is solved(Keyerror:'SSDMobilenetV2 is not in the backbone registry')
but I have the second problem:
I download the checkpoint:
person_vehicle_bike_sd512_mb2_clustered_epoch_21.pth
and used the cfg file:
person-vehicle-bike-detection-crossroad-1016/config.py
when i did like this:
python ../../external/mmdetection/tools/test.py $CONFIGURATION_FILE /home/inbasis/Downloads/mmdetection/demo/person_vehicle_bike_sd512_mb2_clustered_epoch_21.pth --out result.pkl --eval bbox
the result is:
The model and loaded state dict do not match exactly
unexpected key in source state_dict: bbox_head.loss_balancer.weight

**Comment by AlexanderDokuchaev** [comment]
@dhdljd  It's ok. This weights used only for training.

**Comment by nagrjungururaj** [comment]
Hi!

I am trying to folow the tutorial given in the openvino training extensions, mmdetection folder seems to be empty. After this install should I copy the mmdetection folder to openvino_training_extensions ? Another thing is where is init_venv.sh located in this repo ? I couldn't find it. Any help appreciated.

Thanks

**Comment by Ilya-Krylov** [comment]
@nagrjungururaj 
```
cd pytorch_toolkit/object_detection
bash init_venv.sh
. venv/bin/activate
```

It will automatically clone needed mmdetection (from our fork).
