### ISSUE TITLE
A question of Data preparation in the Vehicle Re-Identification

### ISSUE THREAD

**Issue by barryhung4work** [openvinotoolkit/training_extensions#324]
Hi, 
When I work on the [Data preparation](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/object_reidentification/vehicle_reidentification/DATA.md) step in the Vehicle Re-Identification, I cannot not find the the text file "data/makes.txt"  which is referred to the final step to merge CompCars and VMMRdb.

Dose anyone can help? I will appreciate for it.

**Comment by evgeny-izutov** [comment]
Hi,
The correct relative path of the mentioned directory `data` is [pytorch_toolkit/object_reidentification/vehicle_reidentification/data](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/object_reidentification/vehicle_reidentification/data).

**Comment by barryhung4work** [comment]
OK, I have found the makes.txt.
Thanks a lot.
