### ISSUE TITLE
Quantify model acceleration

### ISSUE THREAD

**Issue by blueskywwc** [openvinotoolkit/training_extensions#329]
Hello, how does the quantified model (int8) compare with the original model (fp32) in the acceleration of the inference process? Thank you!

**Comment by brmarkus** [comment]
Do you have a specific model in mind, running on a specific hardware like a CPU with the AVX-512-VNNI instruction-set?

**Comment by druzhkov-paul** [comment]
Acceleration depends on too many things: model itself, inference mode, hardware device used for inference. To get some understanding on the scale of possible acceleration you may try running [Benchmark app](https://github.com/openvinotoolkit/openvino/tree/master/tools/benchmark) from OpenVINO on a target device with models from [OpenVINO Open Model Zoo](https://github.com/openvinotoolkit/open_model_zoo), most of which come with an int8-ready representation out-of-the-box
