### ISSUE TITLE
Person Vehicle Bike Detector : Download and prepare required submodules error

### ISSUE THREAD

**Issue by hsulin0806** [openvinotoolkit/training_extensions#338]
Encountered this error.

**Describe the bug**

bash ../prepare_modules.sh

Please install required packages by follow command and run script again:
$ sudo apt install 2to3 protobuf-compiler

fatal: reference is not a tree: ed842bffd41f6ff38707c4f0968d2cfd91088688
fatal: reference is not a tree: f0899f18e178afb4b57c50ec32a7e8952e6f6a99
Unable to checkout 'ed842bffd41f6ff38707c4f0968d2cfd91088688' in submodule path '../../external/cocoapi'
Unable to checkout 'f0899f18e178afb4b57c50ec32a7e8952e6f6a99' in submodule path '../../external/models'

How can I solve it, thank you.

**Steps to Reproduce**

1.bash ../prepare_modules.sh

**Environment:**
 - OS: Linux Ubuntu 16.04
 - Framework version: TensorFlow
 - Python version:3.6.12
 - OpenVINO version:2020.4
 - CUDA/cuDNN version:9
 - GPU model and memory:32GB

**Comment by Ilya-Krylov** [comment]
Tensorflow-based detection models have been removed from repo.
