### ISSUE TITLE
custom dataset for instance segmentation

### ISSUE THREAD

**Issue by renziver** [openvinotoolkit/training_extensions#347]
Hi, i'm trying to fine tune the instance segmentation model on a custom dataset which is in coco format as well, how can I use it to train  custom model using the instance segmentation in the toolkit? it seems like it is highly coupled on the `coco2017` data on the `segmentoly.get_dataset`  function.

**Comment by druzhkov-paul** [comment]
@renziver 
To support your custom dataset, you should implement your data/annotation reader in a dedicated class, inherited from `InstanceDataset`. You may refer to `COCODataset` as an example. After that register your custom dataset inside `segmentoly.get_dataset` function.

As an option that likely require less coding, you can convert you dataset's annotation to MS COCO format and register an instance of `COCODataset` with proper path to images and annotation in `segmentoly.get_dataset` function.

FYI, we are in the process of current instance segmentation code deprecation in favour of a new [engine](https://github.com/openvinotoolkit/mmdetection). You may try it out already.
