### ISSUE TITLE
Submodules out of date

### ISSUE THREAD

**Issue by pigubaoza** [openvinotoolkit/training_extensions#404]
The submodules inside `/external` are out of date. 
https://github.com/openvinotoolkit/training_extensions/tree/develop/external

This causes issues when trying to run other files. For example, I was running
`python ../tools/instantiate_template.py ${MODEL_TEMPLATE} ${WORK_DIR}`
in the custom detector folder https://github.com/openvinotoolkit/training_extensions/blob/develop/pytorch_toolkit/object_detection/model_templates/custom-detection/readme.md#custom-object-detector
This required me to do a `pip install -r ./requirements.txt`, which requires 
`./../../external/mmdetection/requirements/build.txt`
and this is one of the submodules that is not linked properly right now since https://github.com/opencv/mmaction2 no longer exists.

**Comment by pigubaoza** [comment]
Hi, is anyone able to provide some information about how to correctly get these submodules? I see that several of them are not linked to any github repos, and therefore we are unable to pull them. https://github.com/openvinotoolkit/training_extensions/tree/develop/external

**Comment by Ilya-Krylov** [comment]
I guess there is no problem if you re-clone repo. the mmaction2 and other submodules have been moved to `openvinotoolkit` organization.`

**Comment by pigubaoza** [comment]
a fresh re-clone did indeed solve the problem. thank you
