### ISSUE TITLE
Very nondeterministic results with person-reidentification-retail-0265

### ISSUE THREAD

**Issue by jpsml** [openvinotoolkit/training_extensions#428]
I am trying to extract features from some images using the person-reidentification-retail-0265 model, but the features obtained in different executions are very different. For example, if you compute the cosine distances between the features, you will get very different values depending on the execution. Any way to handle this issue?

**Steps to Reproduce**

1. Download the following images and place them in the root folder of the deep-object-reid project with names `person_01_01.jpg`, `person_01_02.jpg` and `person_02_01.jpg`, respectively:
![person_01_01](https://user-images.githubusercontent.com/13179144/106791281-778c9800-6633-11eb-9a5d-da97e0c50df3.jpg)
![person_01_02](https://user-images.githubusercontent.com/13179144/106791277-76f40180-6633-11eb-999c-44328e54eb6f.jpg)
![person_02_01](https://user-images.githubusercontent.com/13179144/106791279-778c9800-6633-11eb-9a57-5496070f1132.jpg)
2. Download the person-reidentification-retail-0265.pt model file and place it in the folder `"<deep-object-reid root folder>/outputs/reid-0265/"`
3. Place the following script in the root folder of the deep-object-reid project and run it:
```python
import torch

from torchreid.utils import FeatureExtractor

extractor = FeatureExtractor(
    model_name='fpn_osnet_x1_0',
    model_path='outputs/reid-0265/person-reidentification-retail-0265.pt',
    device='cuda'
)

image_list = [
    'person_01_01.jpg',
    'person_01_02.jpg',
    'person_02_01.jpg',
]

features = extractor(image_list)
print(features.shape)

cos = torch.nn.CosineSimilarity(dim=0)
print(1 - cos(features[0, :], features[1, :]))
print(1 - cos(features[0, :], features[2, :]))
print(1 - cos(features[1, :], features[2, :]))
```

**Environment:**
 - OS: Windows 10
 - Framework version: PyTorch 1.2.0
 - Python version: 3.7.9
 - OpenVINO version: not applicable
 - CUDA/cuDNN version: CUDA 10.0
 - GPU model and memory: NVIDIA GeForce GTX 1060

You can find below some examples of outputs that I am getting in different executions of the previous script, please note how different the distances are in different executions:

```
(torchreid-ote) D:\deep-object-reid-ote>python feature_extractor_sample.py
Model: fpn_osnet_x1_0
- params: 2,061,776
- flops: 978,747,024
Successfully loaded pretrained weights from "outputs/reid-0265/person-reidentification-retail-0265.pt"
** The following layers are discarded due to unmatched keys or layer size: ['conv2.1.gate.gn.weight', 'conv2.1.gate.gn.bias', 'conv3.1.gate.gn.weight', 'conv3.1.gate.gn.bias', 'conv4.1.gate.gn.weight', 'conv4.1.gate.gn.bias', 'global_avgpool.weight', 'global_avgpool.bias', 'fc.2.weight', 'classifier.weight', 'in_first.weight', 'in_first.bias']
torch.Size([3, 256])
tensor(0.0660, device='cuda:0')
tensor(0.0274, device='cuda:0')
tensor(0.0949, device='cuda:0')

(torchreid-ote) D:\deep-object-reid-ote>python feature_extractor_sample.py
Model: fpn_osnet_x1_0
- params: 2,061,776
- flops: 978,747,024
Successfully loaded pretrained weights from "outputs/reid-0265/person-reidentification-retail-0265.pt"
** The following layers are discarded due to unmatched keys or layer size: ['conv2.1.gate.gn.weight', 'conv2.1.gate.gn.bias', 'conv3.1.gate.gn.weight', 'conv3.1.gate.gn.bias', 'conv4.1.gate.gn.weight', 'conv4.1.gate.gn.bias', 'global_avgpool.weight', 'global_avgpool.bias', 'fc.2.weight', 'classifier.weight', 'in_first.weight', 'in_first.bias']
torch.Size([3, 256])
tensor(0.1205, device='cuda:0')
tensor(0.0368, device='cuda:0')
tensor(0.1223, device='cuda:0')

(torchreid-ote) D:\deep-object-reid-ote>python feature_extractor_sample.py
Model: fpn_osnet_x1_0
- params: 2,061,776
- flops: 978,747,024
Successfully loaded pretrained weights from "outputs/reid-0265/person-reidentification-retail-0265.pt"
** The following layers are discarded due to unmatched keys or layer size: ['conv2.1.gate.gn.weight', 'conv2.1.gate.gn.bias', 'conv3.1.gate.gn.weight', 'conv3.1.gate.gn.bias', 'conv4.1.gate.gn.weight', 'conv4.1.gate.gn.bias', 'global_avgpool.weight', 'global_avgpool.bias', 'fc.2.weight', 'classifier.weight', 'in_first.weight', 'in_first.bias']
torch.Size([3, 256])
tensor(0.0671, device='cuda:0')
tensor(0.0152, device='cuda:0')
tensor(0.0564, device='cuda:0')
```

**Comment by sovrasov** [comment]
Hi! Please try fix from #439
