### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by Rakshith2597** [openvinotoolkit/training_extensions#446]
- Please provide details regarding how to contribute to this training extension as contribute.md file is not available
- Can we submit training codes to this repository for the inference model being submitted at openmodelzoo?

These submissions are part of the project MIRIAD: Many Incarnations of Screening of Radiology for High Throughput Disease Screening via Multiple Instance Reinforcement Learning with Adversarial Deep Neural Networks, sponsored by INTEL TECHNOLOGY INDIA PVT. LTD.(23-56P, Deverabeesanahalli, Varthur Hobli, Outer Ring Road, Bellandur Post, Bangalore - 560 103) undertaken in the Electrical Engineering of Indian Institute of Technology Kharagpur.
Principal Investigators:

Dr. Debdoot Sheet (PI), Dr. Nirmalya Ghosh (Co-PI)
Department of Electrical Engineering
Indian Institute of Technology Kharagpur

Dr. Ramanathan Sethuraman (Co-PI)
Intel Technology India Pvt. Ltd.

**Comment by Ilya-Krylov** [comment]
https://github.com/openvinotoolkit/training_extensions#contributing
