### ISSUE TITLE
cannot run pytorch_toolkit/tools/instantiate_template.py 

### ISSUE THREAD

**Issue by pigubaoza** [openvinotoolkit/training_extensions#453]
**Describe the bug**
Running the latest develop branch as of 1 March 2021 (Merge: 4db33d0 6758dce), I am unable to run instantiate template.py 
The error I get is as below: 
```
Traceback (most recent call last):
  File "/openvino_training_extensions/pytorch_toolkit/tools/instantiate_template.py", line 61, in <module>
    main()
  File "/openvino_training_extensions/pytorch_toolkit/tools/instantiate_template.py", line 44, in main
    verbose=args.verbose)
  File "/openvino_training_extensions/pytorch_toolkit/ote/ote/utils/misc.py", line 164, in run_through_shell
    executable="/bin/bash")
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Steps to Reproduce**
To make this reproducible, I am running this as a Docker build. 
Prior to this, I have done a `git submodule update` where external/mmaction2 failed after requiring my github.com username and password, saying `fatal: repository 'https://github.com/opencv/mmaction2/' not found`. I then did a `git clone https://github.com/open-mmlab/mmaction2.git`, and `git submodule update --init --recursive`, which said `Unable to checkout 'efd44dac1bb9c2af2975246f0eb2f1d94af640c5' in submodule path 'external/mmaction2'`
external/nncf also failed, but I have done a `git clone  https://github.com/openvinotoolkit/nncf.git` inside /external. 
The problems I have with the submodules seem to be unrelated to the problem I am facing above though. 

My dockerfile is as follows :
```
FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y libturbojpeg python3-tk python3-pip virtualenv cmake ninja-build protobuf-compiler libprotobuf-dev wget git git-lfs
COPY . /openvino_training_extensions
WORKDIR /openvino_training_extensions/pytorch_toolkit/object_detection

RUN ./init_venv.sh
RUN . venv/bin/activate

RUN mkdir /openvino_training_extensions/my_model
ENV MODEL_TEMPLATE='./model_templates/custom-object-detection/mobilenet_v2-2s_ssd-256x256/template.yaml
ENV WORK_DIR='/openvino_training_extensions/my_model'
RUN . venv/bin/activate && python3 /openvino_training_extensions/pytorch_toolkit/tools/instantiate_template.py ${MODEL_TEMPLATE} ${WORK_DIR}
```

**Environment:**
 - OS: Linux Ubuntu 16.04 running in Docker container
 - Framework version: PyTorch
 - Python version: 3
 - OpenVINO version: NA
 - CUDA/cuDNN version: NA
 - GPU model and memory: NA

**Comment by pigubaoza** [comment]
I have done a fresh pull using the following commands
```
git clone --branch develop --recursive https://github.com/openvinotoolkit/openvino_training_extensions.git
cd openvino_training_extensions
git submodule update --init --recursive
```

during building of the Dockerfile, the same error is shown

**Comment by Ilya-Krylov** [comment]
@pigubaoza Hi, you need to use python3.7 or newer, sorry that it is not reflected in documentation. We will fix it.

Also you can try https://github.com/openvinotoolkit/training_extensions/pull/447 if you would not like to use newer versions of python by some reasons.

**Comment by pigubaoza** [comment]
Thanks! Good to hear that the documentation will be fixed to be clearer. I have managed to solve this with some changes. 

For those who are facing similar dependency/environment issue, the below is my Dockerfile which works up to the point of . Feel free to add to it to help others. 

```
FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y software-properties-common

# Installs python 3.7.9, based on instructions from 
# https://ubuntuhandbook.org/index.php/2019/02/install-python-3-7-ubuntu-18-04/
RUN add-apt-repository ppa:ubuntu-toolchain-r/ppa && apt install -y python3.7
RUN rm /usr/bin/python3 && ln -s python3.7 /usr/bin/python3
RUN apt-get update && apt-get install -y libturbojpeg python3-tk python3-pip python3.7-dev virtualenv cmake ninja-build protobuf-compiler libprotobuf-dev wget git git-lfs
COPY . /openvino_training_extensions
WORKDIR /openvino_training_extensions/pytorch_toolkit/object_detection

# Create virtual environment and build mmdetectionm, then activate venv as shown in:
# https://github.com/openvinotoolkit/training_extensions/tree/develop/pytorch_toolkit/object_detection
RUN ./init_venv.sh
RUN . venv/bin/activate

# Select a model template file and instantiate it in some directory
RUN mkdir /openvino_training_extensions/my_model
ENV MODEL_TEMPLATE='./model_templates/custom-object-detection/mobilenet_v2-2s_ssd-256x256/template.yaml'
ENV WORK_DIR='/openvino_training_extensions/my_model'
RUN . venv/bin/activate && python3 /openvino_training_extensions/pytorch_toolkit/tools/instantiate_template.py ${MODEL_TEMPLATE} ${WORK_DIR}

ENV OBJ_DET_DIR=/openvino_training_extensions/pytorch_toolkit/object_detection
ENV TRAIN_ANN_FILE="${OBJ_DET_DIR}/../../data/airport/annotation_example_train.json"
ENV TRAIN_IMG_ROOT="${OBJ_DET_DIR}/../../data/airport/train"
ENV VAL_ANN_FILE="${OBJ_DET_DIR}/../../data/airport/annotation_example_val.json"
ENV VAL_IMG_ROOT="${OBJ_DET_DIR}/../../data/airport/val"
WORKDIR  ${WORK_DIR}
ENV CLASSES="vehicle,person,non-vehicle"

RUN cd /openvino_training_extensions/pytorch_toolkit/object_detection &&\
   . venv/bin/activate && \
   cd /openvino_training_extensions/my_model && \
   python3 train.py \
   --load-weights ${WORK_DIR}/snapshot.pth \
   --train-ann-files ${TRAIN_ANN_FILE} \
   --train-data-roots ${TRAIN_IMG_ROOT} \
   --val-ann-files ${VAL_ANN_FILE} \
   --val-data-roots ${VAL_IMG_ROOT} \
   --save-checkpoints-to ${WORK_DIR}/outputs \
   --classes ${CLASSES}
```

**Comment by pigubaoza** [comment]
After running train.py, the next step is to run eval.py. This is where I faced another issue. The error I got is as follow:

```
[                                                  ] 0/10, elapsed: 0s, ETA:/openvino_training_extensions/pytorch_toolkit/object_detection/venv/lib/python3.7/site-packages/mmcv/utils/registry.py:64: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
/openvino_training_extensions/pytorch_toolkit/object_detection/venv/lib/python3.7/site-packages/nncf/dynamic_graph/wrappers.py:16: UserWarning: You are using DataParallel, which may cause significant performance issues with dynamic graph building. Consider using distributed training (DistributedDataParallel) instead
  warnings.warn("You are using DataParallel, which may cause significant performance issues with dynamic graph "
Traceback (most recent call last):
  File "/openvino_training_extensions/external/mmdetection/tools/test.py", line 188, in <module>
    main()
  File "/openvino_training_extensions/external/mmdetection/tools/test.py", line 169, in main
    args.show_score_thr)
  File "/openvino_training_extensions/external/mmdetection/mmdet/apis/test.py", line 51, in single_gpu_test
    score_thr=show_score_thr)
  File "/openvino_training_extensions/external/mmdetection/mmdet/models/detectors/base.py", line 384, in show_result
    class_names=['' for _ in self.CLASSES] if text_results is not None else self.CLASSES,
UnboundLocalError: local variable 'text_results' referenced before assignment
results are stored in: /tmp/tmp8kuy4_5g
Traceback (most recent call last):
  File "eval.py", line 44, in <module>
    main()
  File "eval.py", line 40, in main
    evaluator(**eval_args)
  File "/openvino_training_extensions/pytorch_toolkit/ote/ote/modules/evaluators/base.py", line 40, in __call__
    self._evaluate_internal(config, snapshot, out, update_config, metrics_functions, **kwargs)
  File "/openvino_training_extensions/pytorch_toolkit/ote/ote/modules/evaluators/base.py", line 64, in _evaluate_internal
    metrics.extend(func(**metric_args))
  File "/openvino_training_extensions/pytorch_toolkit/ote/ote/metrics/detection/common.py", line 99, in coco_ap_eval_det
    return coco_ap_eval(config_path, work_dir, snapshot, update_config, show_dir)
  File "/openvino_training_extensions/pytorch_toolkit/ote/ote/metrics/detection/common.py", line 93, in coco_ap_eval
    update_outputs(outputs, metric_keys, metric_names, average_precision)
  File "/openvino_training_extensions/pytorch_toolkit/ote/ote/metrics/detection/common.py", line 40, in update_outputs
    f'{metric_values} vs {metric_names} vs {metric_keys}'
AssertionError: [] vs ['AP @ [IoU=0.50:0.95]'] vs ['bbox']
```

Is anyone able to help with this?

**Comment by Pked01** [comment]
@pigubaoza 

> After running train.py, the next step is to run eval.py. This is where I faced another issue. The error I got is as follow:
> 
> ```
> [                                                  ] 0/10, elapsed: 0s, ETA:/openvino_training_extensions/pytorch_toolkit/object_detection/venv/lib/python3.7/site-packages/mmcv/utils/registry.py:64: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
>   'The old API of register_module(module, force=False) '
> /openvino_training_extensions/pytorch_toolkit/object_detection/venv/lib/python3.7/site-packages/nncf/dynamic_graph/wrappers.py:16: UserWarning: You are using DataParallel, which may cause significant performance issues with dynamic graph building. Consider using distributed training (DistributedDataParallel) instead
>   warnings.warn("You are using DataParallel, which may cause significant performance issues with dynamic graph "
> Traceback (most recent call last):
>   File "/openvino_training_extensions/external/mmdetection/tools/test.py", line 188, in <module>
>     main()
>   File "/openvino_training_extensions/external/mmdetection/tools/test.py", line 169, in main
>     args.show_score_thr)
>   File "/openvino_training_extensions/external/mmdetection/mmdet/apis/test.py", line 51, in single_gpu_test
>     score_thr=show_score_thr)
>   File "/openvino_training_extensions/external/mmdetection/mmdet/models/detectors/base.py", line 384, in show_result
>     class_names=['' for _ in self.CLASSES] if text_results is not None else self.CLASSES,
> UnboundLocalError: local variable 'text_results' referenced before assignment
> results are stored in: /tmp/tmp8kuy4_5g
> Traceback (most recent call last):
>   File "eval.py", line 44, in <module>
>     main()
>   File "eval.py", line 40, in main
>     evaluator(**eval_args)
>   File "/openvino_training_extensions/pytorch_toolkit/ote/ote/modules/evaluators/base.py", line 40, in __call__
>     self._evaluate_internal(config, snapshot, out, update_config, metrics_functions, **kwargs)
>   File "/openvino_training_extensions/pytorch_toolkit/ote/ote/modules/evaluators/base.py", line 64, in _evaluate_internal
>     metrics.extend(func(**metric_args))
>   File "/openvino_training_extensions/pytorch_toolkit/ote/ote/metrics/detection/common.py", line 99, in coco_ap_eval_det
>     return coco_ap_eval(config_path, work_dir, snapshot, update_config, show_dir)
>   File "/openvino_training_extensions/pytorch_toolkit/ote/ote/metrics/detection/common.py", line 93, in coco_ap_eval
>     update_outputs(outputs, metric_keys, metric_names, average_precision)
>   File "/openvino_training_extensions/pytorch_toolkit/ote/ote/metrics/detection/common.py", line 40, in update_outputs
>     f'{metric_values} vs {metric_names} vs {metric_keys}'
> AssertionError: [] vs ['AP @ [IoU=0.50:0.95]'] vs ['bbox']
> ```
> 
> Is anyone able to help with this?
In my testing 
Error comes only when eval.py passed with parameter --save-output-to

**Comment by Ilya-Krylov** [comment]
Please use recently updated develop branch. There is no such problem. Don't forget to update submodules.
