### ISSUE TITLE
could not connect to server

### ISSUE THREAD

**Issue by Amanda-Barbara** [openvinotoolkit/training_extensions#468]
Running in 451c3f729afb
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: could not connect to server (check repositories file)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: could not connect to server (check repositories file)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
2 errors; 15 distinct packages available
ERROR: Service 'idlp_db' failed to build: The command '/bin/sh -c apk update && apk add --no-cache git' returned a non-zero code: 2
How to solve it ? Thanks!
-->

**Comment by Ilya-Krylov** [comment]
@Amanda-Barbara , we put on hold development of Web UI and removed it from the repo, since it is not currently supported.
