### ISSUE TITLE
Support CUDA 11, Pytorch1.7 and higher

### ISSUE THREAD

**Issue by fangliang425** [openvinotoolkit/training_extensions#500]
Hi,
I got this error while running training of instance segmentation, and found this can be solved by downgrading the pytorch to 1.6
[pytorch/pytorch#47050](https://github.com/pytorch/pytorch/issues/47050), however pytorch 1.6 is incompatible with CUDA 11.

`RuntimeError: replicas_[0].size() == rebuilt_param_indices_.size() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/distributed/c10d/reducer.cpp":1326, please report a bug to PyTorch. rebuilt parameter indices size is not same as original model parameters size.338 versus 213954`

May I ask when the project would support CUDA 11, Pytorch1.7 and higher? As the RTX 30 series GPU becomes mainstreamed gradually, which only supports CUDA 11.

**Comment by Ilya-Krylov** [comment]
This PR will bring support of PyTorch 1.7 and higher https://github.com/openvinotoolkit/training_extensions/pull/510

**Comment by Ilya-Krylov** [comment]
#510 has been merged
