### ISSUE TITLE
Meaning and importance of GPU_NUM in reported results

### ISSUE THREAD

**Issue by manisoftwartist** [openvinotoolkit/training_extensions#549]
Please I would like to know the significance of `GPU_NUM` reported in the detection results on the page
https://github.com/openvinotoolkit/training_extensions/tree/develop/models/object_detection/model_templates/face-detection

**Comment by morkovka1337** [comment]
Hi.

This is just the information about how the model was trained, like other environment info. Specifically, `GPU_NUM` affects the batch size. If you want to reproduce the experiment **with the same batch size**, you will need at least `GPU_NUM` cards.
