### ISSUE TITLE
where is OSNet-IAP?

### ISSUE THREAD

**Issue by AlphaPlusTT** [openvinotoolkit/training_extensions#555]
I can't find the code for OSNet-IAP mentioned in "Building Computationally Efficient and Well-Generalizing Person Re-Identification Models with Metric Learning"

**Comment by sovrasov** [comment]
Hi! The implementation of  OSNet-IAP is actually located in [deep-object-reid](https://github.com/openvinotoolkit/deep-object-reid). There is also [instruction](https://github.com/openvinotoolkit/training_extensions/tree/develop/misc/pytorch_toolkit/object_reidentification/person_reidentification) how to launch training and the original [configs](https://github.com/openvinotoolkit/training_extensions/tree/develop/misc/pytorch_toolkit/object_reidentification/person_reidentification/configs/experimental) from the mentioned paper.

**Comment by morkovka1337** [comment]
Closing this. If you have any other questions, feel free to open a new issue.

**Comment by lighteninglin** [comment]
file not found
