### ISSUE TITLE
mmdetection Version Update

### ISSUE THREAD

**Issue by anujdutt9** [openvinotoolkit/training_extensions#562]
Hi. Is there a timeline by when the `mmdetection` fork for this project will be updated. I am asking this because about 16 days ago they released the `CenterNet, CornerNet` models implementation and I would like to use that from within this framework. But it looks like the `mmdetection` fork here is about 2 months old.
So, is there any timeline on that being updated? Will there be some specific issues that I can encounter if I try to pull the latest version of `mmdetection` to make it work here?
Thanks

**Comment by morkovka1337** [comment]
Hi @anujdutt9!

Currently, we don't have plans to update our mmdetection branch. As for `CornerNet` and `CenterNet`, I guess, it depends on the task you are trying to solve. If you want just to train the model, you can use upstream's mmdetection branch to train using OTE. Upstream supports export to ONNX format, but it is not guaranteed it would work well in OpenVINO IR. If you want to use `CenterNet` in OpenVINO, we have it in our [OpenModelZoo](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/models/public/index.md#object-detection), you can use the ready model.

Thanks.
