### ISSUE TITLE
Documentation about model optimization is missed

### ISSUE THREAD

**Issue by AlexKoff88** [openvinotoolkit/training_extensions#570]
I can successfully train, validate and export the Face Detection model as it is described here: ,/models/object_detection/model_templates/face-detection. But I don't see how can I get an optimized version of it using NNCF.
So, a description for all the enabled optimization methods (INT8 quantization, Filter Pruning) should be added.

The same is applicable to the rest of the templates where we have NNCF enabled.

**Comment by AlexanderDokuchaev** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/569
