### ISSUE TITLE
OpenVINO Model Optimizer is not found or configured improperly

### ISSUE THREAD

**Issue by kbrajwani** [openvinotoolkit/training_extensions#579]
OpenVINO Model Optimizer is not found or configured improperly.

How to install OpenVINO Model Optimizer  in ubuntu.
i have already installed `pip install openvino  openvino-dev` .

**Comment by morkovka1337** [comment]
Hi,

Ho do you run model optimizer?
I have just installed openvino and openvino-dev into ubuntu18 based docker container and `mo -h` works fine for me. Could you please provide code snippet and console output?

**Comment by kbrajwani** [comment]
It's done i was trying to install in colab. You are using mo.py in this file https://github.com/openvinotoolkit/mmdetection/blob/75a1ecdf7f67daf7cf9d2578c86cad885769510e/tools/export.py
is this correct. For now i have just give full path of /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py and it worked.

**Comment by morkovka1337** [comment]
Great! We are using `mo.py` file since previously OpenVINO was installed via separate installer. If you use pip to install openvino, I think, changing `mo.py` to just `mo` will work without setting the full path.
