### ISSUE TITLE
Training/Validation metrics

### ISSUE THREAD

**Issue by WingRS** [openvinotoolkit/training_extensions#590]
HI,
Could you please describe detailed names of each of the metrics that are shown in tesorboard. There are 6 of them, namely:
1. bbox_mAP - I assume just mean average precision for the bounding box, could you point where do you calculate them?
2. bbox_mAP_50 - as far as I understand it's mAP for first 50 closest boxes?
3. bbox_mAP_75 - the same as for 2.? 
4. bbox_mAP_l - this one confuses me, I don't have a guess
5. bbox_mAP_m - no idea, in my case it is just constantly -1
6. bbox_mAP_s - the same as 5.

The logs are nicely done, but it would be cool to have an interface on how to add them. But so far understanding them would be awesome, since I don't recall them from my courses/other projects.

Very much appreciate !

**Comment by Ilya-Krylov** [comment]
It should help https://towardsdatascience.com/on-object-detection-metrics-with-worked-example-216f173ed31e

**Comment by WingRS** [comment]
Thanks for the fast answer, the article has brought some light to my question.
Although, during training on the example dataset (airport), the mAP for large and medium objects left at -1, maybe you would have some insight? thanks!

**Comment by Ilya-Krylov** [comment]
Maybe you don't have large and medium objects in your test annotation?

**Comment by WingRS** [comment]
Thanks for the article and for the fast response!
