### ISSUE TITLE
Normalized image to infer request - trained mobilenet v2 384x384

### ISSUE THREAD

**Issue by WingRS** [openvinotoolkit/training_extensions#592]
Thanks a lot to the team for answering the question. I have used my own dataset in coco format, and to do a simple test on a live cam feed, I am trying to understand how to pass the image to the inference correctly.
So far, usually, I've been doing this:
```
 cv::Mat img_ = image_ptr->image; (image here is in BGR8 format)
  infer_request_ptr_->SetBlob(input_name_, wrapMat2Blob(img_));
```
Though, this seems to be working, I am getting the bounding boxes for the objects (though a fair amount of false positives, but this is only 50 epochs so far, so I think some more training may fix this) - but the class is incorrect in most of the cases.

In the README.md for custom object detection it is written that the image should be in **planar BGR format and normalized**, is this the right procedure:
```
  cv::Mat img_ = image_ptr->image;
  cv::Mat dst;
  cv::normalize(img_, dst,1,0, cv::NORM_MINMAX,-1, cv::noArray());
  infer_request_ptr_->SetBlob(input_name_, wrapMat2Blob(dst));
```
After doing this, there are no detections at all, so I think I am doing something wrong. I'll keep investigating and looking for mistakes, but maybe somebody can spot the problem immediately?

**Comment by Ilya-Krylov** [comment]
you can use/learn Open Model Zoo demo https://github.com/openvinotoolkit/open_model_zoo/tree/develop/demos/object_detection_demo/cpp
