### ISSUE TITLE
Why this repo does not provide example for training semantic segmentation?

### ISSUE THREAD

**Issue by franva** [openvinotoolkit/training_extensions#595]
I have seen the Instance Segmentation, appreciate for the code.

But there are many demands on semantic segmentation, and for some edge  devices(actually most of them) are not capable of doing the instance segmentation e.g. OAK-D , OAK-1 cameras, RPi etc. why don't we provide the code for training Semantic Segmentation models??

**Comment by druzhkov-paul** [comment]
@franva Thanks for the request. We are considering that.

**Comment by sovrasov** [comment]
Now we have semantic segmentation component as well: https://github.com/openvinotoolkit/training_extensions/tree/master/external#semantic-segmentaion
