### ISSUE TITLE
Exporting a model that was compressed by filter pruning algorithm in combination with another compression algorithm is not yet supporting

### ISSUE THREAD

**Issue by pkcktkksh98** [openvinotoolkit/training_extensions#597]
<pre>NotImplementedError: Exporting a model that was compressed by filter pruning algorithm in combination with another compression algorithm is not yet supporting
Traceback (most recent call last):
  File &quot;export.py&quot;, line 41, in &lt;module&gt;
    main()
  File &quot;export.py&quot;, line 37, in main
    exporter(ote_args)
  File &quot;/home/afiqkazu/training_extensions/ote/ote/modules/exporters/base.py&quot;, line 31, in __call__
    self._export_to_openvino(args, tools_dir)
  File &quot;/home/afiqkazu/training_extensions/ote/ote/modules/exporters/mmdetection.py&quot;, line 51, in _export_to_openvino
    run_through_shell(f&apos;python3 {os.path.join(tools_dir, &quot;export.py&quot;)} &apos;
  File &quot;/home/afiqkazu/training_extensions/ote/ote/utils/misc.py&quot;, line 161, in run_through_shell
    return subprocess.run(cmd,
  File &quot;/usr/lib/python3.8/subprocess.py&quot;, line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command &apos;python3 /home/afiqkazu/training_extensions/external/mmdetection/tools/export.py model.py outputs2/latest.pth export2  --opset=11 openvino --input_format BGR&apos; returned non-zero exit status 1.
</pre>

I was wondering if you are working on supporting to export a model that was compressed by filter pruning algorithm?

**Comment by alexsu52** [comment]
@pkcktkksh98, Thank you for your question! Yes, we are working on supporting to export a model that was compressed by the filter pruning algorithm. Stay tuned.
