### ISSUE TITLE
Cannot use Intel DG1

### ISSUE THREAD

**Issue by JustinKJChen** [openvinotoolkit/training_extensions#617]
**Is your feature request related to a problem? Please describe.**

Doing transfer learning in Intel Tiger Lake with DG1 but still using CPU for model re-train.

**Describe the solution you'd like to propose.**

Model retrain via DG1 GPU

**Describe alternatives you've considered**

**Additional context**

**Comment by morkovka1337** [comment]
Hi,

For now we only support training on NVIDIA GPUs with cuda backend.
