### ISSUE TITLE
Deterministic runs of train.py

### ISSUE THREAD

**Issue by manisoftwartist** [openvinotoolkit/training_extensions#641]
**Is your feature request related to a problem? Please describe.**
It is hard to reproduce training results between two different runs when using `tools/train.py`

**Describe the solution you'd like to propose.**
The mmdetection backend has 2 arguments `seed` and `deterministic` which if we set through `train.py`, can solve this issue. 

There is a  [related question](https://github.com/openvinotoolkit/training_extensions/issues/638) I have created which if answered, can help me implement this feature myself. And I will give a pull request.

**Comment by morkovka1337** [comment]
@manisoftwartist is this relevant now? If now, I will close the issue.

**Comment by sungmanc** [comment]
Close this issue, please reopen it if there is any problem.
