### ISSUE TITLE
Can't find train.py for Text Spotter

### ISSUE THREAD

**Issue by huynhcuong98** [openvinotoolkit/training_extensions#645]
Hi, 
I am trying to train YAMTS model for my data. But i can not see any train.py. Can you show me please, thanks!

**Comment by npduyduc** [comment]
Hi, morkovka1337
I have the same problem as anhcuong98, I did step #2 from the readme, this is what i get:
`cp -r /home/training_extensions/models/text_spotting/model_templates/alphanumeric-text-spotting/text-spotting-0005\* --target-directory=/tmp/my-text-spotting-0005
INFO:root:Downloading https://storage.openvinotoolkit.org/repositories/openvino_training_extensions/models/text_spotting/alphanumeric_text_spotting/text_spotting_0005/epoch_25.pth
INFO:root:Downloading https://storage.openvinotoolkit.org/repositories/openvino_training_extensions/models/text_spotting/alphanumeric_text_spotting/text_spotting_0005/epoch_25.pth has been completed.`

And in /tmp/my-text-spotting-0005 there are only empty folders "packages" and snapshot.pth, and nothing more.
So I can't find the file "export.py" to try step 3
Can you explan for me what did I miss ?
Thanks you!

**Comment by morkovka1337** [comment]
Hi, @npduyduc!

Sorry for the late reply, did not see this earlier.

I have completed all the steps from 1 to 2, and I have the following structure of the model template folder:
```
(text_spotting)➜  /tmp/my-text-spotting-0005 ls                           
compress.py  eval.py  export.py  model.py  modules.yaml  packages  requirements.txt  snapshot.pth  template.yaml  train.py
```

Make sure you have completed all the steps from the readme (incl. step 1)
