### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'modules.yaml'

### ISSUE THREAD

**Issue by atheeraa** [openvinotoolkit/training_extensions#678]
Hello, 
I'm trying to follow the basic usage of gesture recognition model, 
I'm getting the following error when running step 3.b 

FileNotFoundError: [Errno 2] No such file or directory: 'modules.yaml'

Could you tell me how to fix it? 

Thank you!

**Comment by morkovka1337** [comment]
Hi,

Which model template you are trying to export? I have just tested `s3d-rgb-mobilenet-v3-stream-msasl/template.yaml`, and it works as expected. Make sure, you have completed all the previous steps before 3b.
