### ISSUE TITLE
Query regarding contributing guidelines

### ISSUE THREAD

**Issue by Rakshith2597** [openvinotoolkit/training_extensions#684]
I had previously submitted a model for [chest_xray_screening](https://github.com/openvinotoolkit/training_extensions/tree/master/misc/pytorch_toolkit/chest_xray_screening) following the criteria mentioned in the [CONTRIBUTING.md](https://github.com/openvinotoolkit/training_extensions/blob/master/CONTRIBUTING.md) file. The criteria that are mentioned in the CONTRIBUTING.md file seems to be no longer applicable for the develop branch in its current state. I wish to make some modifications on  [chest_xray_screening](https://github.com/openvinotoolkit/training_extensions/tree/master/misc/pytorch_toolkit/chest_xray_screening) and submit new models as well. Kindly let me know if I shall stick to the guidelines in [CONTRIBUTING.md](https://github.com/openvinotoolkit/training_extensions/blob/master/CONTRIBUTING.md) file.

---
_This is part of the project MIRIAD: Many Incarnations of Screening of Radiology for High Throughput Disease Screening via Multiple Instance Reinforcement Learning with Adversarial Deep Neural Networks, sponsored by INTEL TECHNOLOGY INDIA PVT. LTD._

_Principal Investigators:
Dr Debdoot Sheet (PI), Dr Nirmalya Ghosh (Co-PI)
Department of Electrical Engineering
Indian Institute of Technology Kharagpur_

_Dr Ramanathan Sethuraman (Co-PI)
Intel Technology India Pvt. Ltd._

**Comment by Ilya-Krylov** [comment]
You can contribute to 'master' branch, 'develop' is not default branch, it is experimental

**Comment by morkovka1337** [comment]
Hi,

Thank you. Contributing guide has been updated.
