### ISSUE TITLE
Gesture Recognetion - Unable to download MS-ASL Data set

### ISSUE THREAD

**Issue by HannanAbdullah** [openvinotoolkit/training_extensions#696]
Thanks a lot for the great work.
I am using ubuntu 20.04 and I installed the last version of openvino tool kit and Cuda 11.
I reached step 4.a Downloading the MS-ASL data set in gesture recognition model. 
After execute the following commands
```
python3 ./tools/data/download_msasl_videos.py \
  -s ${DATA_DIR}/msasl_data/MSASL_train.json ${DATA_DIR}/msasl_data/MSASL_val.json ${DATA_DIR}/msasl_data/MSASL_test.json \
  -o ${DATA_DIR}/msasl_data/videos

```
I got this error !

![Screenshot from 2021-11-13 10-41-53](https://user-images.githubusercontent.com/17067019/141610668-f065a76b-ec9b-441c-99bb-53c5d8e421ac.png)

I think some videos are private! 

![Screenshot from 2021-11-13 13-35-04](https://user-images.githubusercontent.com/17067019/141615356-3fcb92aa-848f-40bf-8b20-88f66844788f.png)

Thanks

**Comment by morkovka1337** [comment]
Hi,

I think, in this case we can do nothing, we do not own any rights on the videos.
