### ISSUE TITLE
Some questions about project

### ISSUE THREAD

**Issue by jnzw** [openvinotoolkit/training_extensions#726]
Hi @Ilya-Krylov @morkovka1337 ,

We are working on adding a handwritten text recognition model to the open model zoo (https://github.com/openvinotoolkit/open_model_zoo/pull/2917) (https://gitlab-icv.inn.intel.com/algo/model-zoo-models-intel/-/merge_requests/945), and would also like to contribute to training_extensions so that our customer can train with their own data.  Could you please answer a few questions:
1. Our model is an Intel internal PyTorch model, if I open a pull request, should it be added under `misc/pytorch_toolkit/text_recognition` or the `models` folder?
2. How/Where do we upload pre-trained checkpoint .pth file?
3. Is there a release schedule for training_extensions (we are aiming for 2022.1)?

Thanks

**Comment by morkovka1337** [comment]
Hi, @jnzw!

1. I think it would be the most appropriate way to keep the training code consistent. 
2. We usually upload our models to the [openvino cloud model storage](https://storage.openvinotoolkit.org/repositories/openvino_training_extensions/models)
3. Can not say for sure right now, maybe Ilya has more information about this.

For any further questions you can also email me on the work email address (it is in my profile) or PM me in teams (for faster communication).
